services:
  postgres-db:
    container_name: postgresDb
    image: postgres:16.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersvc
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - '25432:5432'
      - '6432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared

volumes:
  postgres-data:
