/*
 * This file is generated by jOOQ.
 */
package ru.mai.user.jooq.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class User(
    var id: Long? = null,
    var name: String? = null,
    var password: String? = null,
    var email: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: User = other as User
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.name == null) {
            if (o.name != null)
                return false
        }
        else if (this.name != o.name)
            return false
        if (this.password == null) {
            if (o.password != null)
                return false
        }
        else if (this.password != o.password)
            return false
        if (this.email == null) {
            if (o.email != null)
                return false
        }
        else if (this.email != o.email)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.name == null) 0 else this.name.hashCode())
        result = prime * result + (if (this.password == null) 0 else this.password.hashCode())
        result = prime * result + (if (this.email == null) 0 else this.email.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("User (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(password)
        sb.append(", ").append(email)

        sb.append(")")
        return sb.toString()
    }
}
