CREATE SCHEMA IF NOT EXISTS usersvc;

CREATE TABLE IF NOT EXISTS usersvc.user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_recurrent_order PRIMARY KEY,
    name     varchar(160) NOT NULL,
    password text         NOT NULL,
    email    varchar(160)
);