/*
 * This file is generated by jOOQ.
 */
package ru.mai.user.jooq.tables.references


import ru.mai.user.jooq.tables.User



/**
 * The table <code>usersvc.user</code>.
 */
val USER: User = User.USER
